server:
  port: 8080

spring:
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: avaliacao_movie-service
          uri: http://localhost:8001
          predicates:
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies
        - id: avaliacao_catalog-service
          uri: http://localhost:8002
          predicates:
            - Path=/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog

queue:
  movie:
    name: MovieQueue


