server:
  port: 8002
  servlet:
    context-path: /catalog/

spring:
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

mensagem: hello catalog

management:
  endpoints:
    web:
      exposure:
        include: '*'
